# Generated by Django 4.0.3 on 2023-06-29 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XFactorAuth',
            fields=[
                ('auth_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=150)),
                ('auth_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='XFactorDeploy',
            fields=[
                ('deploy_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=150)),
                ('deploy_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='XFactorGroup',
            fields=[
                ('group_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=150)),
                ('group_note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XFactorProgram',
            fields=[
                ('program_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='XFactorUser',
            fields=[
                ('computer_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('computer_name', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('user_email', models.CharField(max_length=150, null=True)),
                ('user_dep', models.CharField(max_length=50, null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('chasisstype', models.CharField(max_length=50)),
                ('domain_id', models.CharField(max_length=150, null=True)),
                ('open_id', models.CharField(max_length=150, null=True)),
                ('os_simple', models.CharField(max_length=50)),
                ('os_total', models.CharField(max_length=150)),
                ('os_version', models.CharField(max_length=150)),
                ('os_build', models.CharField(max_length=150)),
                ('hw_list', models.TextField()),
                ('sw_list', models.TextField()),
                ('hotfix', models.CharField(max_length=150, null=True)),
                ('hotfix_date', models.DateTimeField(null=True)),
                ('user_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='XFactorUserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.CharField(max_length=150)),
                ('auth_id', models.CharField(max_length=150)),
                ('auth_use', models.CharField(max_length=150)),
                ('xfactor_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactorauth')),
                ('xfactor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactoruser')),
            ],
        ),
        migrations.CreateModel(
            name='XFactorProgramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.CharField(max_length=150)),
                ('program_id', models.CharField(max_length=150)),
                ('program_installed', models.CharField(max_length=150)),
                ('xfactor_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactorprogram')),
                ('xfactor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactoruser')),
            ],
        ),
        migrations.CreateModel(
            name='XFactorLog',
            fields=[
                ('log_num', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=150)),
                ('deploy_name', models.CharField(max_length=150)),
                ('deploy_time', models.DateTimeField()),
                ('deploy_result', models.CharField(max_length=150)),
                ('xfactor_deploy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactordeploy')),
                ('xfactor_roup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactorgroup')),
            ],
        ),
        migrations.CreateModel(
            name='XFactorGroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.CharField(max_length=150)),
                ('group_id', models.CharField(max_length=150)),
                ('xfactor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactorgroup')),
                ('xfactor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactoruser')),
            ],
        ),
        migrations.AddField(
            model_name='xfactordeploy',
            name='xfactor_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactorgroup'),
        ),
    ]
