# Generated by Django 4.0.3 on 2023-07-11 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Statistics',
            fields=[
                ('daily_statistics_num', models.IntegerField(primary_key=True, serialize=False)),
                ('classification', models.CharField(max_length=100)),
                ('item', models.TextField()),
                ('item_count', models.CharField(max_length=100)),
                ('statistics_collection_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='XFactor_Auth',
            fields=[
                ('auth_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=150)),
                ('auth_url', models.CharField(max_length=150)),
                ('auth_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='XFactor_Group',
            fields=[
                ('group_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=150)),
                ('group_note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XFactor_Log',
            fields=[
                ('log_num', models.IntegerField(primary_key=True, serialize=False)),
                ('log_func', models.CharField(max_length=150)),
                ('log_item', models.CharField(max_length=150)),
                ('log_result', models.CharField(max_length=150)),
                ('log_user', models.CharField(max_length=100)),
                ('log_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='XFactor_Program',
            fields=[
                ('program_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='XFactor_User',
            fields=[
                ('computer_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('computer_name', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('user_email', models.CharField(max_length=150, null=True)),
                ('user_dep', models.CharField(max_length=50, null=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('chasisstype', models.CharField(max_length=50)),
                ('domain_id', models.CharField(max_length=150, null=True)),
                ('open_id', models.CharField(max_length=150, null=True)),
                ('os_simple', models.CharField(max_length=50)),
                ('os_total', models.CharField(max_length=150)),
                ('os_version', models.CharField(max_length=150)),
                ('os_build', models.CharField(max_length=150)),
                ('hw_list', models.TextField()),
                ('sw_list', models.TextField()),
                ('hotfix', models.CharField(max_length=150, null=True)),
                ('hotfix_date', models.DateTimeField(null=True)),
                ('user_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='XFactor_UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.CharField(max_length=150)),
                ('auth_id', models.CharField(max_length=150)),
                ('auth_use', models.CharField(max_length=150)),
                ('xfactor_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactor_auth')),
                ('xfactor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactor_user')),
            ],
        ),
        migrations.CreateModel(
            name='XFactor_ProgramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.CharField(max_length=150)),
                ('program_id', models.CharField(max_length=150)),
                ('program_installed', models.CharField(max_length=150)),
                ('xfactor_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactor_program')),
                ('xfactor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactor_user')),
            ],
        ),
        migrations.CreateModel(
            name='XFactor_GroupUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_id', models.CharField(max_length=150)),
                ('group_id', models.CharField(max_length=150)),
                ('xfactor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactor_group')),
                ('xfactor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactor_user')),
            ],
        ),
        migrations.CreateModel(
            name='XFactor_Deploy',
            fields=[
                ('deploy_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('group_id', models.CharField(max_length=150)),
                ('deploy_name', models.CharField(max_length=150)),
                ('xfactor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactor_group')),
            ],
        ),
    ]
