# Generated by Django 4.0.3 on 2023-06-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='XFactorAuth',
            new_name='XFactor_Auth',
        ),
        migrations.RenameModel(
            old_name='XFactorDeploy',
            new_name='XFactor_Deploy',
        ),
        migrations.RenameModel(
            old_name='XFactorGroup',
            new_name='XFactor_Group',
        ),
        migrations.RenameModel(
            old_name='XFactorGroupUser',
            new_name='XFactor_GroupUser',
        ),
        migrations.RenameModel(
            old_name='XFactorLog',
            new_name='XFactor_Log',
        ),
        migrations.RenameModel(
            old_name='XFactorProgram',
            new_name='XFactor_Program',
        ),
        migrations.RenameModel(
            old_name='XFactorProgramUser',
            new_name='XFactor_ProgramUser',
        ),
        migrations.RenameModel(
            old_name='XFactorUser',
            new_name='XFactor_User',
        ),
        migrations.RenameModel(
            old_name='XFactorUserAuth',
            new_name='XFactor_UserAuth',
        ),
    ]
