# Generated by Django 4.0.3 on 2023-07-14 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_xfactor_user_memo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XFactor_Nano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, null=True)),
                ('user_email', models.CharField(max_length=150, null=True)),
                ('user_dep', models.CharField(max_length=50, null=True)),
                ('domain_id', models.CharField(max_length=150, null=True)),
                ('open_id', models.CharField(max_length=150, null=True)),
                ('memo', models.TextField(null=True)),
                ('xfactor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.xfactor_user')),
            ],
        ),
    ]
